### PR TITLE
Add missing inflected forms to glossary and remove unused terms

### PR DESCRIPTION
**Pull request by apasel422**
This is not ready to be merged yet, as there are still some terms flagged by `m-070` that I'm investigating.

Identified in https://github.com/standardebooks/tools/pull/732.

### CODE REVIEW

**Comment by apasel422** [comment]
There are a few things left that I'm not sure about:

1. [`savo`](https://github.com/standardebooks/george-borrow_lavengro/blob/0277ad8df73109e92a6adec5974f59dd1c03729e/src/epub/glossary-search-key-map.xml#L739) is listed in the `<search-key-map>`, but [the corresponding definition](https://github.com/standardebooks/george-borrow_lavengro/blob/0277ad8df73109e92a6adec5974f59dd1c03729e/src/epub/text/glossary.xhtml#L1446) has an acute accent on the `o`. In any case, neither the accented nor unaccented form appears in the text, so I'm inclined to remove it from the `<search-key-map>`.
2. [`loovu`](https://github.com/standardebooks/george-borrow_lavengro/blob/0277ad8df73109e92a6adec5974f59dd1c03729e/src/epub/glossary-search-key-map.xml#L476) only appears in the text as part of `dloovu`, but each word has its own definition in the glossary. Unfortunately for `loovu` [that definition](https://github.com/standardebooks/george-borrow_lavengro/blob/0277ad8df73109e92a6adec5974f59dd1c03729e/src/epub/text/glossary.xhtml#L927) is just `See.`, which is ambiguous as to whether `dloovu` *means* the verb `see` or whether it is an instruction to the reader to look at the immediately following entry for `lovó`. Based on context, the latter is the intent, but in general, there are a number of similar problems in this glossary and I wonder if it makes sense editorially to clean it up a bit in that regard by using multiple `<dt>`s for the same `<dd>`.
3. [`dukker`](https://github.com/standardebooks/george-borrow_lavengro/blob/0277ad8df73109e92a6adec5974f59dd1c03729e/src/epub/glossary-search-key-map.xml#L254) does not appear in the text as is, but rather as other seemingly inflected forms. As such, I'm inclined to remove it from the `<search-key-map>`.
4. [`boró`](https://github.com/standardebooks/george-borrow_lavengro/blob/0277ad8df73109e92a6adec5974f59dd1c03729e/src/epub/glossary-search-key-map.xml#L68) appears with the acute accent on the second `o` only [in the glossary](https://github.com/standardebooks/george-borrow_lavengro/blob/0277ad8df73109e92a6adec5974f59dd1c03729e/src/epub/text/glossary.xhtml#L140). Elsewhere it seems to be written without one, e.g. [here](https://github.com/standardebooks/george-borrow_lavengro/blob/0277ad8df73109e92a6adec5974f59dd1c03729e/src/epub/text/chapter-1-54.xhtml#L61). I'm not sure if the text is in error, or the glossary, or if the difference is intentional.

**Comment by acabal** [comment]
>     1. [`savo`](https://github.com/standardebooks/george-borrow_lavengro/blob/0277ad8df73109e92a6adec5974f59dd1c03729e/src/epub/glossary-search-key-map.xml#L739) is listed in the `<search-key-map>`, but [the corresponding definition](https://github.com/standardebooks/george-borrow_lavengro/blob/0277ad8df73109e92a6adec5974f59dd1c03729e/src/epub/text/glossary.xhtml#L1446) has an acute accent on the `o`. In any case, neither the accented nor unaccented form appears in the text, so I'm inclined to remove it from the `<search-key-map>`.

Yes, remove

>     2. [`loovu`](https://github.com/standardebooks/george-borrow_lavengro/blob/0277ad8df73109e92a6adec5974f59dd1c03729e/src/epub/glossary-search-key-map.xml#L476) only appears in the text as part of `dloovu`, but each word has its own definition in the glossary. Unfortunately for `loovu` [that definition](https://github.com/standardebooks/george-borrow_lavengro/blob/0277ad8df73109e92a6adec5974f59dd1c03729e/src/epub/text/glossary.xhtml#L927) is just `See.`, which is ambiguous as to whether `dloovu` _means_ the verb `see` or whether it is an instruction to the reader to look at the immediately following entry for `lovó`. Based on context, the latter is the intent, but in general, there are a number of similar problems in this glossary and I wonder if it makes sense editorially to clean it up a bit in that regard by using multiple `<dt>`s for the same `<dd>`.

Did David forget to include a link? What does the definition of `loovu` look like in the page scans? I'm not opposed to a cleanup but we should confirm with the scans to make sure it's not our transcription that's the problem.

>     3. [`dukker`](https://github.com/standardebooks/george-borrow_lavengro/blob/0277ad8df73109e92a6adec5974f59dd1c03729e/src/epub/glossary-search-key-map.xml#L254) does not appear in the text as is, but rather as other seemingly inflected forms. As such, I'm inclined to remove it from the `<search-key-map>`.

This sounds like another case of where we should have the root somewhere in the search key map, say if the user selects just the `dukker` portion of the longer inflected word.

>     4. [`boró`](https://github.com/standardebooks/george-borrow_lavengro/blob/0277ad8df73109e92a6adec5974f59dd1c03729e/src/epub/glossary-search-key-map.xml#L68) appears with the acute accent on the second `o` only [in the glossary](https://github.com/standardebooks/george-borrow_lavengro/blob/0277ad8df73109e92a6adec5974f59dd1c03729e/src/epub/text/glossary.xhtml#L140). Elsewhere it seems to be written without one, e.g. [here](https://github.com/standardebooks/george-borrow_lavengro/blob/0277ad8df73109e92a6adec5974f59dd1c03729e/src/epub/text/chapter-1-54.xhtml#L61). I'm not sure if the text is in error, or the glossary, or if the difference is intentional.

Check the page scans, and if the page scans disagree then go with the one that occurs more often.

**Comment by apasel422** [comment]
I've removed `savo`, but I think items 2-4 need to be investigated by a subject-matter expert.

**Comment by acabal** [comment]
We don't have any Romanian subject matter experts, just make your best judgement. It can always be fixed later if someone more knowledgeable comes around.

**Comment by apasel422** [comment]
> What does the definition of `loovu` look like in the page scans?

It [seems to match what we have](https://www.google.com/books/edition/The_Romany_Rye/9eNcwZld6I4C?hl=en&gbpv=1&pg=PA391&printsec=frontcover). I've decided to just remove the `loovu` search term, since there's already one for `dloovu` and I'm not sure why a reader would highlight only the last five characters of a word they're unfamiliar with and whose morpheme structure they are presumably also unfamiliar with. That said, we should still probably make the editorial decision to replace `See.` with `See <a href="#lovo">lovó</a>.`

> Check the page scans, and if the page scans disagree then go with the one that occurs more often.

Unfortunately [the scan is cut off on Google Books](https://www.google.com/books/edition/The_Romany_Rye/9eNcwZld6I4C?hl=en&gbpv=1&pg=PA389&printsec=frontcover), but Project Gutenberg seems to match what we have, so I've chosen to add the unaccented version as an additional `<value/>` and retain the accented form, since otherwise it's a bit weird that the glossary spells it that way but searching for it won't find it.

> This sounds like another case of where we should have the root somewhere in the search key map, say if the user selects just the `dukker` portion of the longer inflected word.

Done.

**Comment by acabal** [comment]
OK, thanks! Does this wrap it up for m-070 or is there still more to do?

**Comment by apasel422** [comment]
@acabal That should be it! Thanks for your guidance.

**Comment by acabal** [comment]
OK, so is the m-070 PR ready to go as-is or did it need further tweaks after all?

**Comment by apasel422** [comment]
It's ready.

**Pull request merged**
